### ISSUE TITLE
Authorship question

### ISSUE THREAD

**Issue by telemachus** [TheThirdOne/BuildYourOwnLispGitbook#15]
I just came across the [online edition of this on Gitbook](https://www.gitbook.io/book/landersbenjamin/buildyourownlisp), and it strikes me as wrong that the author is listed as "Benjamin Landers" and not "Daniel Holden". 

My understanding is that you did the conversion to Gitbook format, and that's terrific, but the content is still Daniel's. At the very least, his name should _also_ be prominent on Gitbook.

Thanks.

**Comment by TheThirdOne** [comment]
You are absolutely right. Daniel should have his name on it. However, I don't know how to add his name. (I am assuming having a collaborator would do so). I will probably talk to him about this.

**Comment by TheThirdOne** [comment]
I just realized I also failed to mention that it is a port on the main page.

**Comment by TheThirdOne** [comment]
I have now gotten Daniel listed under authors and mentioned that it is a port on the front page.

**Comment by telemachus** [comment]
Thanks for taking care of this so fast. And again thank you for all your work making the book available as a Gitbook.
