### ISSUE TITLE
"Reference" not work

### ISSUE THREAD

**Issue by xcodebuild** [TheThirdOne/BuildYourOwnLispGitbook#18]
The **reference code** of  [http://www.buildyourownlisp.com/](http://www.buildyourownlisp.com/) can be toggled by click.But seems **not work** in this gitbook

In [http://www.buildyourownlisp.com/](http://www.buildyourownlisp.com/),it looks like

![refer](https://cloud.githubusercontent.com/assets/5436704/4010141/44756ad6-29f0-11e4-8e7b-193385b8ef95.jpg)

**Comment by TheThirdOne** [comment]
This is a known issue. I just haven't fixed it yet. I would be very open to a pull request.

**Comment by TheThirdOne** [comment]
I have moved all code to separate files; hopefully this is a good enough solution. If you can think of a better solution, please tell me, but for now, I am going to close this.
