### ISSUE TITLE
Update GitBook

### ISSUE THREAD

**Issue by AaronO** [TheThirdOne/BuildYourOwnLispGitbook#4]
@TheThirdOne Great work on porting this book to GitBook.

I was wondering if you would be willing to update to a newer version of GitBook, which has many fixes and improvements as well as radically different & better default theme (check http://gitbookio.github.io/javascript/).

Simply update `gitbook` through `npm`, `rebuild` and push to `gh-pages`.

We like your book a lot, so it's one of the books we've chosen to feature on the new version of `gitbook.io` (coming out later today).

**Comment by TheThirdOne** [comment]
I am having some trouble updating gitbook. The theme is still a dark theme rather than the light theme I have seen in http://gitbookio.github.io/javascript/.

**Comment by TheThirdOne** [comment]
Nevermind, I'm an idiot.

**Comment by TheThirdOne** [comment]
it is updated.

**Comment by AaronO** [comment]
Thanks :+1:
